### ISSUE TITLE
No data received for a while

### ISSUE THREAD

**Issue by LoveMyData** [otherchirps/orange_city_council#1]
Contacted council about the dead link

From: council@orange.nsw.gov.au [mailto:council@orange.nsw.gov.au] 
Sent: Thursday, 22 September 2016 3:21 PM
To: Council Incoming council@orange.nsw.gov.au
Subject: Web Site Contact Form

Enquiry/Comments:
On council web site, on the right hand side, I clicked on 'lodge or find a Development Application' but it lead to an error page.

Can you please investigate?

**Comment by LoveMyData** [comment]
Date: 22 September 2016 at 15:53
Subject: Orange City Council web site.

Thanks for your query about the error on the Orange City Council web site.

That page has been disconnected because of an error in the search facility which handles Development Applications.

Work is under way to fix that problem but I’m not able to say when it will be working again.

Some text is in place on that page to advise of the problem.

With thanks for your patience.

**Comment by otherchirps** [comment]
Awesome.  Thanks for letting me know.  Will keep an eye on the council site for updates.

**Comment by otherchirps** [comment]
Looks like orange council has their DA search back online.  The planningalerts scraper already picked it up, and just ran my own instance successfully.
